name: Build and save my Docker image to a registry
 
on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'  # déclenche seulement si backend change --
 
env:
  REGISTRY: "acrinfobi22210.azurecr.io" # Nom de la registry Azure
  IMAGE_NAME: "backend-pye"              # Nom de votre image Docker
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Login Azure Container Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} --password-stdin
 
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f src/backend/Dockerfile src/backend
 
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}